### ISSUE TITLE
How to integrate it with flutter..?

### ISSUE THREAD

**Issue by prateekmedia** [TheAssassin/appimagecraft#10]
Hi, I found out that this library is great when you want to automate appimage building using CI's. Could you help me integrate this to Flutter projects, I can share the directory structure for reference if you want to guide me, also it uses CMAKE and ninja.

**Comment by TheAssassin** [comment]
I am not sure what flutter is, or what would have to be done to integrate this tool into it. Please elaborate.

**Comment by prateekmedia** [comment]
> I am not sure what flutter is, or what would have to be done to integrate this tool into it. Please elaborate.

[Flutter](https://flutter.dev) is a crossplataform framework used to build `cross platform applications`. 

Example of this is [the latest installer](https://github.com/canonical/ubuntu-desktop-installer) that is being build by the Ubuntu team. It uses flutter and it integrates well with the ubuntu theme.


Also it uses gtk as a base for linux so it just `compiles it to native gtk C code`.  

But the problem is that the `instructions given for the gtk app here are not general` and includes many things that I can't understand and as your readme says most the developers only want copy n paste so that was not the case I found when copy pasting.

Also `I managed to create AppName.AppDir/usr/ and other related structures` using a bash script after building for linux but I dont know `how to proceed`.

**Comment by TheAssassin** [comment]
How are those applications built? What build tool is typically used? CMake?

**Comment by prateekmedia** [comment]
> How are those applications built? What build tool is typically used? CMake?

Yeah, cmake and ninja, and they are then dumped into a temp dir something like `build/outputs/linux`.

**Comment by prateekmedia** [comment]
Nevermind I followed this [arcticle](https://odilondamasceno.medium.com/creating-appimage-with-flutter-d19ef8b53158) and everything worked,
