### ISSUE TITLE
would like to include system dependencies(i.e. glibc) which appimage-builder does

### ISSUE THREAD

**Issue by jpercyasnet** [TheAssassin/appimagecraft#11]
Basically would like an enhancement to incorporate appimage-builder so I can include the glibc.
If not, can appimagecraft have the option of preserving the AppDir so I can run the appimage-builder?

**Comment by TheAssassin** [comment]
We could in the long term add support for tools which do that. However, linuxdeploy isn't the right tool for this.

New issues/PRs to support new tools other than linuxdeploy are welcome.
