### ISSUE TITLE
Version command used incorrectly

### ISSUE THREAD

**Issue by elsuizo** [TheAssassin/appimagecraft#14]
Hi I'm trying to use this to generate an appimage inside a github action and I get an error when running the build:

```bash
/dummy-rust-cli/.appimagecraft-build-script-todj3a74/build.sh: line 15: 1.0: command not found
```
is missing some dependencies??? 
this is the original repo:

https://github.com/elsuizo/dummy-rust-cli

Thanks in advance

**Comment by TheAssassin** [comment]
https://github.com/elsuizo/dummy-rust-cli/blob/master/appimagecraft.yml#L6

Replace `version_command` with `version` or put a shell snippet (e.g., `echo 1.0`) into `version_command`. The command is typically used so one does not have to maintain a version inside the YAML file.

**Comment by elsuizo** [comment]
Now i got:

```bash
make: *** No rule to make target 'install'.  Stop.
```
Is there a way to see the generated scripts?

**Comment by TheAssassin** [comment]
Of course, that's the whole point of this generator. Just run `appimagecraft genscripts -d <outdir>`, with `<outdir>` being the directory of choice.
