### ISSUE TITLE
Upload to GH Releases

### ISSUE THREAD

**Issue by tyu1996** [TheAssassin/appimagecraft#2]
I'm interested on this and I think I'm early into this game.

I get a rough idea on appimagecraft can automate the AppImage build task easier compared to Travis-CI (I feel the difficulty while contributing to a repo). 

Already read two examples provided, what I guess about 'appimage:' section in appimagecraft.yml is the deployment of AppImage. I might missing something else that I concern: will this tool helps on **uploading** the built AppImage to GH Releases?

**Comment by tyu1996** [comment]
BTW, may I know what Python framework you used to develop appimagecraft, and the Python version?

**Comment by TheAssassin** [comment]
> I'm interested on this and I think I'm early into this game.

Good to hear that. And yes, you are.

This project isn't supposed to fully replace Travis CI. Its purpose is mainly to reduce the amount of "script code" a user has to write to build their project, and to streamline and standardize the AppImage creation process.

appimagecraft is still pretty new and not completely stable (`.yml` format wise). Lots of features could be added (such as support for many other build systems).

I didn't use any specific Python framework, the dependencies are listed in `setup.py`. I'm developing with Python 3.6 or newer.

**Comment by TheAssassin** [comment]
Uploading artifacts to GitHub releases and other systems is probably a good idea. However, as this project is merely a shell script generator, we need to use separate tools which can be called from the generated scripts to upload files. You might want to checkout https://github.com/probonopd/uploadtool.

**Comment by tyu1996** [comment]
Cool. I will want to participate and contribute to this project in technical side. It'll not in this moment, am busying for my final semester study, soon will be. May I know recently which part can I contribute to?

**Comment by TheAssassin** [comment]
I hardly have time to work on this project unfortunately right now. This week I plan to spend most time on appimagelint. Perhaps we'll talk once you're ready to get started? 

In general, docs would be nice to have, where the user is shown how to use the project, etc. But there's way more to do. There's some structural problems that need to be fixed before adding more code.

**Comment by TheAssassin** [comment]
I recommend using https://github.com/TheAssassin/pyuploadtool, which does this much better. appimagecraft should focus on uploading. It shouldn't be very hard to add another step to a CI script. pyuploadtool supports GitHub releases very well.
